const characterMap = [
    { value: '*', label: ' ' },
    { value: 'A', label: 'Black' },
    { value: 'B', label: 'Red' },
    { value: 'C', label: 'Blue' },
    { value: 'D', label: 'Green' },
    { value: 'E', label: 'Yellow' },
    { value: 'F', label: 'Purple' },
    { value: 'G', label: 'Brown' },
    { value: 'H', label: 'Pink' },
    { value: 'I', label: 'Orange' },
    { value: 'J', label: 'Gray' },
    { value: 'K', label: 'White' },
    { value: 'L', label: 'Infrared' },
    { value: 'M', label: 'Navy' },
    { value: 'N', label: 'Olive' },
    { value: 'O', label: 'Magenta' },
    { value: 'P', label: 'Lavender' },
    { value: 'Q', label: 'Cyan' },
    { value: 'R', label: 'Maroon' },
    { value: 'S', label: 'Indigo' },
    { value: 'T', label: 'Lime' },
    { value: 'U', label: 'Turquoise' },
    { value: 'V', label: 'Peach' },
    { value: 'W', label: 'Salmon' },
    { value: 'X', label: 'Mint' },
    { value: 'Y', label: 'Slate' },
    { value: 'Z', label: 'Mustard' },
    { value: '9', label: 'Lilac' },
    { value: '8', label: 'Ruby' },
    { value: '7', label: 'Pear' },
    { value: '6', label: 'Sienna' },
    { value: '5', label: 'Sky' },
    { value: '4', label: 'Charcoal' },
    { value: '3', label: 'Burgundy' },
    { value: '2', label: 'Amber' },
    { value: '1', label: 'Plum' },
    { value: '0', label: 'Azure' },
];

export default characterMap;
