const characterMap = [
    { value: '*', label: ' ' },
    { value: '0', label: '0' },
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '5', label: '5' },
    { value: '6', label: '6' },
    { value: '7', label: '7' },
    { value: '8', label: '8' },
    { value: '9', label: '9' },
    { value: 'Z', label: '10' },
    { value: 'Y', label: '11' },
    { value: 'X', label: '12' },
    { value: 'W', label: '13' },
    { value: 'V', label: '14' },
    { value: 'U', label: '15' },
    { value: 'T', label: '16' },
    { value: 'S', label: '17' },
    { value: 'R', label: '18' },
    { value: 'Q', label: '19' },
    { value: 'P', label: '20' },
    { value: 'O', label: '21' },
    { value: 'N', label: '22' },
    { value: 'M', label: '23' },
    { value: 'L', label: '24' },
    { value: 'K', label: '25' },
    { value: 'J', label: '26' },
    { value: 'I', label: '27' },
    { value: 'H', label: '28' },
    { value: 'G', label: '29' },
    { value: 'F', label: '30' },
    { value: 'E', label: '31' },
    { value: 'D', label: '32' },
    { value: 'C', label: '33' },
    { value: 'B', label: '34' },
    { value: 'A', label: '35' },
    // Add more options as needed
];

export default characterMap;
