const characterMap = [
    { value: '*', label: ' ' },
    { value: 'A', label: 'United States' },
    { value: 'B', label: 'United Kingdom' },
    { value: 'C', label: 'Canada' },
    { value: 'D', label: 'Australia' },
    { value: 'E', label: 'Germany' },
    { value: 'F', label: 'France' },
    { value: 'G', label: 'Italy' },
    { value: 'H', label: 'Japan' },
    { value: 'I', label: 'South Korea' },
    { value: 'J', label: 'NATO (North Atlantic Treaty Organization)' },
    { value: 'K', label: 'Israel' },
    { value: 'L', label: 'New Zealand' },
    { value: 'M', label: 'Mexico' },
    { value: 'N', label: 'Philippines' },
    { value: 'O', label: 'Thailand' },
    { value: 'P', label: 'Pakistan' },
    { value: 'Q', label: 'Saudi Arabia' },
    { value: 'R', label: 'Jordan' },
    { value: 'S', label: 'Egypt' },
    { value: 'T', label: 'Morocco' },
    { value: 'U', label: 'Singapore' },
    { value: 'V', label: 'Taiwan' },
    { value: 'W', label: 'Turkey' },
    { value: 'X', label: 'Indonesia' },
    { value: 'Y', label: 'Malaysia' },
    { value: 'Z', label: 'South Africa' },
    { value: '0', label: 'India' },
    { value: '1', label: 'Afghanistan' },
    { value: '2', label: 'Iraq' },
    { value: '3', label: 'United Arab Emirates' },
    { value: '4', label: 'Qatar' },
    { value: '5', label: 'Kuwait' },
    { value: '6', label: 'Bahrain' },
    { value: '7', label: 'Oman' },
    { value: '8', label: 'Yemen' },
    { value: '9', label: 'Lebanon' },
];

export default characterMap;
