// characterMap.js
const characterMap = [
    { value: '*', label: ' ' },
    { value: 'A', label: '79' },
    { value: 'B', label: '77' },
    { value: 'C', label: '75' },
    { value: 'D', label: '73' },
    { value: 'E', label: '71' },
    { value: 'F', label: '69' },
    { value: 'G', label: '67' },
    { value: 'H', label: '65' },
    { value: 'I', label: '63' },
    { value: 'J', label: '61' },
    { value: 'K', label: '59' },
    { value: 'L', label: '57' },
    { value: 'M', label: '55' },
    { value: 'N', label: '53' },
    { value: 'O', label: '51' },
    { value: 'P', label: '49' },
    { value: 'Q', label: '47' },
    { value: 'R', label: '45' },
    { value: 'S', label: '43' },
    { value: 'T', label: '41' },
    { value: 'U', label: '39' },
    { value: 'V', label: '37' },
    { value: 'W', label: '35' },
    { value: 'X', label: '33' },
    { value: 'Y', label: '31' },
    { value: 'Z', label: '29' },
    { value: '9', label: '27' },
    { value: '8', label: '25' },
    { value: '7', label: '23' },
    { value: '6', label: '21' },
    { value: '5', label: '19' },
    { value: '4', label: '17' }, 
    { value: '3', label: '15' },
    { value: '2', label: '13' },
    { value: '1', label: '11' },
    { value: '0', label: '< 9' },
    // Add more mappings as needed
];

export default characterMap;
