const characterMap = [
    { value: '*', label: ' ' },
    { value: 'A', label: '350+' },
    { value: 'B', label: '350' },
    { value: 'C', label: '340' },
    { value: 'D', label: '330' },
    { value: 'E', label: '320' },
    { value: 'F', label: '310' },
    { value: 'G', label: '300' },
    { value: 'H', label: '290' },
    { value: 'I', label: '280' },
    { value: 'J', label: '270' },
    { value: 'K', label: '260' },
    { value: 'L', label: '250' },
    { value: 'M', label: '240' },
    { value: 'N', label: '230' },
    { value: 'O', label: '220' },
    { value: 'P', label: '210' },
    { value: 'Q', label: '200' },
    { value: 'R', label: '190' },
    { value: 'S', label: '180' },
    { value: 'T', label: '170' },
    { value: 'U', label: '160' },
    { value: 'V', label: '150' },
    { value: 'W', label: '140' },
    { value: 'X', label: '130' },
    { value: 'Y', label: '120' },
    { value: 'Z', label: '110' },
    { value: '9', label: '100' },
    { value: '8', label: '90' },
    { value: '7', label: '80' },
    { value: '6', label: '70' },
    { value: '5', label: '60' },
    { value: '4', label: '50' },
    { value: '3', label: '40' },
    { value: '2', label: '30' },
    { value: '1', label: '20' },
    { value: '0', label: '10' },
    // Add more options as needed
];

export default characterMap;