const characterMap = [
    { value: '*', label: ' ' },
    { value: 'B', label: 'UNKNOWN' },
    { value: 'C', label: '8+' },
    { value: 'D', label: '8' },
    { value: 'E', label: '7.75' },
    { value: 'F', label: '7.5' },
    { value: 'G', label: '7.25' },
    { value: 'H', label: '7' },
    { value: 'I', label: '6.75' },
    { value: 'J', label: '6.5' },
    { value: 'K', label: '6.25' },
    { value: 'L', label: '6' },
    { value: 'M', label: '5.75' },
    { value: 'N', label: '5.5' },
    { value: 'O', label: '5.25' },
    { value: 'P', label: '5' },
    { value: 'Q', label: '4.75' },
    { value: 'R', label: '4.5' },
    { value: 'S', label: '4.25' },
    { value: 'T', label: '4' },
    { value: 'U', label: '3.75' },
    { value: 'V', label: '3.5' },
    { value: 'W', label: '3.25' },
    { value: 'X', label: '3' },
    { value: 'Y', label: '2.75' },
    { value: 'Z', label: '2.5' },
    { value: '9', label: '2.25' },
    { value: '8', label: '2' },
    { value: '7', label: '1.75' },
    { value: '6', label: '1.5' },
    { value: '5', label: '1.25' },
    { value: '4', label: '1' },
    { value: '3', label: '0.75' },
    { value: '2', label: '0.5' },
    { value: '1', label: '0.25' },
    { value: '0', label: '0' },
    // Add more options as needed
];

export default characterMap;