const characterMap = [
    { value: '*', label: ' ' },
    { value: 'A', label: '200+' },
    { value: 'B', label: '200' },
    { value: 'C', label: '195' },
    { value: 'D', label: '190' },
    { value: 'E', label: '185' },
    { value: 'F', label: '180' },
    { value: 'G', label: '175' },
    { value: 'H', label: '170' },
    { value: 'I', label: '165' },
    { value: 'J', label: '160' },
    { value: 'K', label: '155' },
    { value: 'L', label: '150' },
    { value: 'M', label: '145' },
    { value: 'N', label: '140' },
    { value: 'O', label: '135' },
    { value: 'P', label: '130' },
    { value: 'Q', label: '125' },
    { value: 'R', label: '120' },
    { value: 'S', label: '115' },
    { value: 'T', label: '110' },
    { value: 'U', label: '105' },
    { value: 'V', label: '100' },
    { value: 'W', label: '95' },
    { value: 'X', label: '90' },
    { value: 'Y', label: '85' },
    { value: 'Z', label: '80' },
    { value: '9', label: '75' },
    { value: '8', label: '70' },
    { value: '7', label: '65' },
    { value: '6', label: '60' },
    { value: '5', label: '55' },
    { value: '4', label: '50' },
    { value: '3', label: '45' },
    { value: '2', label: '40' },
    { value: '1', label: '35' },
    { value: '0', label: '30' },
    // Add more options as needed
];

export default characterMap;